# Generated by Django 3.1.7 on 2021-04-06 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('-date_posted',)},
        ),
        migrations.RenameField(
            model_name='question',
            old_name='title',
            new_name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='content',
        ),
    ]
