# Generated by Django 3.1.7 on 2021-04-07 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_answer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='user',
        ),
    ]
