# Generated by Django 3.1.7 on 2021-04-07 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_answer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='user',
        ),
    ]
